class ContactState:
    NUEVO = "NUEVO"
    CONTACTADO = "CONTACTADO"
    RESPONDIO = "RESPONDIO"
    INTERESADO_CARRERA = "INTERESADO_CARRERA"
    INTERESADO_ADMISION = "INTERESADO_ADMISION"
    INTERESADO_BECA = "INTERESADO_BECA"
    PIDIO_PORTAL = "PIDIO_PORTAL"
    PIDIO_CONTACTO = "PIDIO_CONTACTO"
    SALIR = "SALIR"
    NO_INTERESADO = "NO_INTERESADO"
    RATE_LIMITED = "RATE_LIMITED"
    ERROR_ENVIO = "ERROR_ENVIO"


CAMPAIGN_EXCLUDED_STATES = {ContactState.SALIR, ContactState.NO_INTERESADO}
